version: "3.9"

services:
  mongo_database:
    image: mongo:7
    container_name: medqueue-mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_INITDB_ROOT_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_INITDB_ROOT_PASSWORD}
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db
      - ./database/init:/docker-entrypoint-initdb.d

  api_service:
    build: ./api_service
    container_name: medqueue-api
    env_file:
      - .env
    depends_on:
      - mongo_database
      - ml_service
    ports:
      - "8000:8000"

  ml_service:
    build: ./ml_service
    container_name: medqueue-ml
    env_file:
      - .env
    ports:
      - "8001:8001"

volumes:
  mongo_data:
