name: Lint Python Services

on: [push, pull_request]

jobs:
  lint:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        subdir: [api_service, ml_service]

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"

      - name: Install dependencies
        if: ${{ hashFiles(format('{0}/**/*.py', matrix.subdir)) != '' }}
        run: |
          cd ${{ matrix.subdir }}
          python -m pip install --upgrade pip
          pip install pylint black

      - name: Lint with Pylint
        if: ${{ hashFiles(format('{0}/**/*.py', matrix.subdir)) != '' }}
        run: |
          cd ${{ matrix.subdir }}
          pylint **/*.py

      - name: Check formatting with Black
        if: ${{ hashFiles(format('{0}/**/*.py', matrix.subdir)) != '' }}
        run: |
          cd ${{ matrix.subdir }}
          black --check .